import { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import { motion, useScroll, useTransform } from 'framer-motion'
import TournamentCard from '../components/tournament/TournamentCard'
import NoticeBoard    from '../components/ui/NoticeBoard'
import useAuthStore   from '../store/useAuthStore'
import { tournamentAPI, userAPI } from '../services/api'
